<!-- EverMedia.csproj -->
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>EverMedia</AssemblyName>
    <RootNamespace>EverMedia</RootNamespace>
    <Version>26.04.10</Version>
    <IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediaBrowser.Server.Core" Version="4.9.1.90" />
    <PackageReference Include="LiteDB" Version="5.0.19" />
    <PackageReference Include="ILRepack.Lib.MSBuild.Task" Version="2.0.34.2" PrivateAssets="All" ExcludeAssets="build;buildTransitive;buildMultitargeting" GeneratePathProperty="true" />
  </ItemGroup>

  <UsingTask TaskName="ILRepack" AssemblyFile="$(PkgILRepack_Lib_MSBuild_Task)\build\ILRepack.Lib.MSBuild.Task.dll" />

  <Target Name="ILRepacker" AfterTargets="Build">
    <ItemGroup>
      <InputAssemblies Include="$(OutputPath)\$(AssemblyName).dll" />
      <InputAssemblies Include="$(OutputPath)\LiteDB.dll" />
      <ILRepackLibraryPath Include="@(ReferencePathWithRefAssemblies->'%(RootDir)%(Directory)')" />
    </ItemGroup>
    <ILRepack Parallel="true" Internalize="true" DebugInfo="false" InputAssemblies="@(InputAssemblies)" LibraryPath="@(ILRepackLibraryPath)" OutputFile="$(OutputPath)\$(AssemblyName).dll" TargetKind="Dll" />
  </Target>

  <ItemGroup>
    <EmbeddedResource Include="EverMediaLogo.png" />
  </ItemGroup>

</Project>
